server:
  port: 8769

spring:
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    product-service-url:
      path: /product/**
      serviceId: product-server
    order-service-url:
      path: /order/**
      serviceId: order-server
  host:
    maxTotalConnections: 10000
    maxPerRouteConnections: 10000
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
    semaphore:
      max-semaphores: 200
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
  SocketTimeout: 10000
