server:
  port: 8082

spring:
  application:
    name: order-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.254.77:3306/order_system?characterEncoding=utf-8&useSSL=false
    username: root
    password:
  redis:
    host: 122.51.254.77
    port: 6379
    timeout: 10000
    database: 0
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
redisson:
  address: redis://122.51.254.77:6379
  password:
mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.example.orderserver.*.po
  typeEnumsPackage: com.example.orderserver.*.po.enums
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    refresh: true
    banner: false
    db-config:
      db-type: mysql
      id-type: AUTO
      field-strategy: not_empty
      capital-mode: true
      logic-delete-value: 1
      logic-not-delete-value: 0


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/







